/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdmin;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.Customer;
import Business.UserAccount.User;
import javax.swing.JPanel;

/**
 *
 * @author chenchen
 */
public class SystemAdminOverviewPanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    /**
     * Creates new form SystemAdminOverviewPanel
     */
    public SystemAdminOverviewPanel(EcoSystem system, JPanel rightPanel) {
        initComponents();
        this.system=system;
        this.rightPanel=rightPanel;
        lbNet.setText("Network Number:    "+system.getNetworkList().size());
        int numEnter = 0;
        int numEmp = 0;
        int numCus = 0;
        for(Network network : system.getNetworkList()){
           numEnter += network.getEnterpriseDirectory().getEnterpriseList().size();
           for(Enterprise enterprise :network.getEnterpriseDirectory().getEnterpriseList() ){
               for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                   numEmp += organization.getEmployeeDirectory().getEmployeeList().size();
               }
           }
        }
        for(User u : system.getUserAccountDirectory().getUserAccountList()){
            if(u.getType().equals("customer")){
                numCus++;
            }
        }
        lbEnter.setText("Enterprise Number:    "+ numEnter);
        lbEmp.setText("Employee Number:    "+ numEmp);
        lbCus.setText("Customer Number:    "+numCus);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbNet = new javax.swing.JLabel();
        lbEnter = new javax.swing.JLabel();
        lbCus = new javax.swing.JLabel();
        lbEmp = new javax.swing.JLabel();

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Love Read Application System");
        lbTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbNet.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbNet.setText("Network Number: ");

        lbEnter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbEnter.setText("Enterprise Number: ");

        lbCus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbCus.setText("Customer Number: ");

        lbEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbEmp.setText("Employee Number: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lbNet, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(lbEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCus, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbNet, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCus;
    private javax.swing.JLabel lbEmp;
    private javax.swing.JLabel lbEnter;
    private javax.swing.JLabel lbNet;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
