/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ControllerPanel;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Interface.Employee.BookManagerWorkArea;
import Interface.Employee.BookSupplierWorkArea;
import Interface.Employee.CommunityManagerWorkArea;
import Interface.Employee.EmployeeWorkQueueOutPanel;
import Interface.Employee.EmployeeWorkQueuePanel;
import Interface.Employee.SHCheckerWorkArea;
import Interface.Employee.SHManagerWorkArea;
import Interface.MainFrame;
import java.awt.CardLayout;

/**
 *
 * @author chenchen
 */
public class EmployeeControlPanel extends javax.swing.JPanel {

    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private Employee employee;
    private Organization organization;
    /**
     * Creates new form EmployeeControlPanel
     */
    public EmployeeControlPanel(EcoSystem system, Employee employee, javax.swing.JSplitPane jSplitPane1, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.employee = employee;
        this.organization = employee.getOrg();
        this.jSplitPane1 = jSplitPane1;
        this.rightPanel = rightPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRein = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        btnRein.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRein.setText("WorkQueue Received In");
        btnRein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnOut.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnOut.setText("WorkQueue Sent Out");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRein, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnHome)
                .addGap(68, 68, 68)
                .addComponent(btnRein)
                .addGap(71, 71, 71)
                .addComponent(btnOut)
                .addGap(67, 67, 67)
                .addComponent(btnLogout)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        EmployeeWorkQueuePanel panel = new EmployeeWorkQueuePanel(system,employee,rightPanel);
        rightPanel.add("EmployeeWorkQueuePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnReinActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        javax.swing.JPanel leftPanel = MainFrame.getLeft();
        jSplitPane1.setLeftComponent(leftPanel);
        rightPanel.removeAll();
        rightPanel.add(new javax.swing.JPanel());
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        EmployeeWorkQueueOutPanel panel = new EmployeeWorkQueueOutPanel(system,employee,rightPanel);
        rightPanel.add("EmployeeWorkQueueOutPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnOutActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        if(employee.getOrg().getType().equals(Organization.Type.BookManage)){
            BookManagerWorkArea panel = new BookManagerWorkArea(system,employee,rightPanel);
            rightPanel.add("BookManagerWorkArea", panel);
        }
        else if(employee.getOrg().getType().equals(Organization.Type.Community)){
            CommunityManagerWorkArea panel = new CommunityManagerWorkArea(system,employee,rightPanel);
            rightPanel.add("CommunityManagerWorkArea", panel);
        }
        else if(employee.getOrg().getType().equals(Organization.Type.Sales)){
            BookSupplierWorkArea panel = new BookSupplierWorkArea(system,employee,rightPanel);
            rightPanel.add("BookSupplierWorkArea", panel);
        }
        else if(employee.getOrg().getType().equals(Organization.Type.Pricing)){
            SHCheckerWorkArea panel = new SHCheckerWorkArea(system,employee,rightPanel);
            rightPanel.add("SHCheckerWorkArea", panel);
        }
        else{
            SHManagerWorkArea panel = new SHManagerWorkArea(system,employee,rightPanel);
            rightPanel.add("SHManagerWorkArea", panel);
        }
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnRein;
    // End of variables declaration//GEN-END:variables
}
