/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import Business.Person;
import java.awt.Image;
import javax.swing.JOptionPane;

/**
 *
 * @author yanhongchen
 */
public class CreatePanel4 extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel4
     */
    private Person person = new Person();
    public CreatePanel4(Person person) {
        initComponents();
        this.person=person; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        licenseNumTextField = new javax.swing.JTextField();
        issuedDateTextField = new javax.swing.JTextField();
        bloodTypeTextField = new javax.swing.JTextField();
        expirationDateTextField = new javax.swing.JTextField();
        pathTextField = new javax.swing.JTextField();
        imageLable = new javax.swing.JLabel();
        attBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        licenseNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(licenseNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 159, 39));

        issuedDateTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(issuedDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 159, 39));

        bloodTypeTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(bloodTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 159, 39));

        expirationDateTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(expirationDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 159, 39));

        pathTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });
        add(pathTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 287, 39));
        add(imageLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 159, 52));

        attBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        attBtn.setText("Addath");
        attBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attBtnActionPerformed(evt);
            }
        });
        add(attBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 159, 42));

        createBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 159, 42));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Issued Date :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, 32));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("License Number :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 32));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Blood Type :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 150, 32));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Expiration Dare :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 150, 32));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("Create Driver License");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 18, 273, 38));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Picture Upload :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 32));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Path:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void attBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i = chooser.showOpenDialog(null);
        if(i == chooser.APPROVE_OPTION){
        String driverPicture = chooser.getSelectedFile().getAbsolutePath();
        String name =chooser.getSelectedFile().getName();
        System.out.println(driverPicture+name);
        pathTextField.setText(driverPicture);
        }else{
        System.out.println("unable to find out");
        }
        //Driver driver = new Driver();
        ImageIcon icon= new ImageIcon(person.getDriver().getPicture());
        icon.setImage(icon.getImage().getScaledInstance(45, 16, Image.SCALE_DEFAULT));
        imageLable.setIcon(icon);
        
       
        //chooser.showOpenDialog(null);
        //person f=chooser.getSelectedFile();
      //  String filename=f.getAbsolutePath();
    //    pathTextField.setText(filename);
        
    }//GEN-LAST:event_attBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        person.getDriver().setLicenseNum(licenseNumTextField.getText());
        person.getDriver().setIssuedDate(issuedDateTextField.getText());
        person.getDriver().setExpirationDate(expirationDateTextField.getText());
        person.getDriver().setBloodType(bloodTypeTextField.getText());
        person.getDriver().setPicture(pathTextField.getText());
        JOptionPane.showMessageDialog(null,"Create Diver Info succesfully!");
    }//GEN-LAST:event_createBtnActionPerformed

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attBtn;
    private javax.swing.JTextField bloodTypeTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField expirationDateTextField;
    private javax.swing.JLabel imageLable;
    private javax.swing.JTextField issuedDateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JTextField pathTextField;
    // End of variables declaration//GEN-END:variables
}
