/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import javax.swing.JOptionPane;

/**
 *
 * @author yanhongchen
 */
public class CreatePanel5 extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel5
     */
    private Person person = new Person();
    public CreatePanel5(Person person) {
        initComponents();
        this.person=person; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alergy1TextField = new javax.swing.JTextField();
        alergy2TextField = new javax.swing.JTextField();
        alergy3TextField = new javax.swing.JTextField();
        medicalNumTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(500, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Create Medical Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 290, 33));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Alergy 1 :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Alergy 2 :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Alergy 3 :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Medical Number :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        alergy1TextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(alergy1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 130, -1));

        alergy2TextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(alergy2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, -1));

        alergy3TextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(alergy3TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 130, -1));

        medicalNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(medicalNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, -1));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        person.getMedical().setMedicalNum(medicalNumTextField.getText());
        person.getMedical().setAlergy1(alergy1TextField.getText());
        person.getMedical().setAlergy2(alergy2TextField.getText());
        person.getMedical().setAlergy3(alergy3TextField.getText());
        JOptionPane.showMessageDialog(null,"Create Medical Info succesfully!");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergy1TextField;
    private javax.swing.JTextField alergy2TextField;
    private javax.swing.JTextField alergy3TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField medicalNumTextField;
    // End of variables declaration//GEN-END:variables
}
