/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import javax.swing.JOptionPane;
/**
 *
 * @author yanhongchen
 */
public class CreatePanel1 extends javax.swing.JPanel {

    /**
     * Creates new form CreatePanel1
     */
    private Person person = new Person();
    public CreatePanel1(Person person) {
        initComponents();
        this.person=person; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        createBtn = new javax.swing.JButton();
        ssnTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        firstnameTextField = new javax.swing.JTextField();
        birthTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Weight :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Social security number :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Height :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Date of birth :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Age :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Phone number :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("LastName :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        createBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        ssnTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(ssnTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 164, -1));

        weightTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(weightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 164, -1));

        heightTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(heightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 164, -1));

        ageTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 164, -1));

        lastnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(lastnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 164, -1));

        firstnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(firstnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 164, -1));

        birthTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(birthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 164, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("FirstName :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        phoneTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 164, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("Create Demografic Info");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        person.getDemographic().setFirstName(firstnameTextField.getText());
        person.getDemographic().setLastName(lastnameTextField.getText());
        person.getDemographic().setAge(ageTextField.getText());
        person.getDemographic().setBirth(birthTextField.getText());
        person.getDemographic().setHeight(heightTextField.getText());
        person.getDemographic().setWeight(weightTextField.getText());
        person.getDemographic().setSsn(ssnTextField.getText());
        person.getDemographic().setPhoneNum(phoneTextField.getText());
        JOptionPane.showMessageDialog(null,"Create Demografic Info succesfully!");
    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField birthTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
