/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
//import Business.Address;
//import Business.Bankaccount;
//import Business.Demographic;
//import Business.Driver;
//import Business.Medical;
                                
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author yanhongchen
 */
public class PrintPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrintPanel
     */
    private  Person person = new Person();
    public PrintPanel (Person person) {
        initComponents();
        displayPerson(person);
    }
private void displayPerson(Person person){
    
    
    String personFirstName=person.getDemographic().getFirstName();
    String personLastName=person.getDemographic().getLastName();
    String personPhoneNum=person.getDemographic().getPhoneNum();
    String personBirth=person.getDemographic().getBirth();
    String personAge=person.getDemographic().getAge();
    String personHeight=person.getDemographic().getHeight();
    String personWeight=person.getDemographic().getWeight();  
    String personSsn=person.getDemographic().getSsn();
    
    String personStreet=person.getAddress().getStreet();
    String personCity=person.getAddress().getCity();
    String personState=person.getAddress().getState();
    String personZip=person.getAddress().getZip();
    
    String personSName=person.getBankaccount().getsName();
    String personSRoutingNum=person.getBankaccount().getsRoutingNum();
    String personSAccountNum=person.getBankaccount().getsAccountNum();
    String personSAccountBal=person.getBankaccount().getsAccountBal();
    
    String personCName=person.getBankaccount().getcName();
    String personCRoutingNum=person.getBankaccount().getcRoutingNum();
    String personCAccountNum=person.getBankaccount().getcAccountNum();
    String personCAccountBal=person.getBankaccount().getcAccountBal();

    String personLicenseNum=person.getDriver().getLicenseNum();
    String personIssuedDate=person.getDriver().getIssuedDate();
    String personExpirationDate=person.getDriver().getExpirationDate();
    String personBloodType=person.getDriver().getBloodType();
    
    String personMedicalNum=person.getMedical().getMedicalNum();
    String personAlergy1=person.getMedical().getAlergy1();
    String personAlergy2=person.getMedical().getAlergy2();
    String personAlergy3=person.getMedical().getAlergy3();
     
    
    
    
    
    demographicTextArea.setText(
            "-----------Demografic Info:-----------"+"\n"+
            "Firstname:"+personFirstName+"\n"+
            "Lastname:"+personLastName+"\n"+
            "PhoneNumber:"+personPhoneNum+"\n"+
            "Birth:"+personBirth+"\t"+
            "Age:"+personAge+"\n"+
            "Height:"+personHeight+"\t"+
            "Weight:"+personWeight+"\n"+
            "Ssn:"+personSsn+"\n\n"+
                  
            "-----------Address Info:-----------"+"\n"+
            "Street:"+personStreet+"\t"+
            "City:"+personCity+"\n"+
            "State:"+personState+"\t"+
            "Zip:"+personZip+"\n\n"+
            
            "-----------Bank Account Info:-------"+"\n"+     
            "Saving Account Name:"+personSName+"\n"+
            "Saving Routing Number:"+personSRoutingNum+"\n"+
            "Saving Account Number:"+personSAccountNum+"\n"+       
            "Saving Account Balence:"+personSAccountBal+"\n"+
            "Checking Account Name:"+personCName+"\n"+
            "Checking Routing Number:"+personCRoutingNum+"\n"+
            "Checking Account Number:"+personCAccountNum+"\n"+       
            "Checking Account Balence:"+personCAccountBal+"\n\n"+
            
            "-----------Driver Info:-----------"+"\n"+
            "License Number:"+personLicenseNum+"\n"+
            "Issued Date:"+personIssuedDate+"\t"+
            "Expiration Date:"+personExpirationDate+"\n"+
            "Blood Type:"+personBloodType+"\n\n"+
                                                 
             "-----------Medical Info:-----------"+"\n"+
            "Medical Number:"+personMedicalNum+"\n"+
            "Alergy1:"+personAlergy1+"\n"+
            "Alergy2:"+personAlergy2+"\n"+
            "Alergy3:"+personAlergy3+"\n"
  
    );
    
    
    
    ImageIcon icon= new ImageIcon(person.getDriver().getPicture());
    icon.setImage(icon.getImage().getScaledInstance(180, 160, Image.SCALE_DEFAULT));
    pictureLabel.setIcon(icon);
    
   
}
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        demographicTextArea = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pictureLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Person Image :"));
        add(pictureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, 180));

        demographicTextArea.setColumns(20);
        demographicTextArea.setRows(5);
        demographicTextArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Person Information:"));
        jScrollPane1.setViewportView(demographicTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, 320, 430));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea demographicTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pictureLabel;
    // End of variables declaration//GEN-END:variables

  
}
