/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;

/**
 *
 * @author yanhongchen
 */
public class ViewPanel1 extends javax.swing.JPanel {
    
    /**
     * Creates new form ViewPanel1
     */
    private  Person person = new Person();
    public ViewPanel1(Person person) {
        initComponents();
        this.person = person;
        displayDemographic(person);
    }

    public void displayDemographic(Person person){
 
    String personFirstName=person.getDemographic().getFirstName();
    firstnameTextField.setText(personFirstName);
    
    String personLastName=person.getDemographic().getLastName();
    lastnameTextField.setText(personLastName);
    
    String personAge=person.getDemographic().getAge();
    ageTextField.setText(personAge);
    
    String personWeight=person.getDemographic().getWeight();
    weightTextField.setText(personWeight);
    
    String personHeight=person.getDemographic().getHeight();
    heightTextField.setText(personHeight);
    
    String personSsn=person.getDemographic().getSsn();
    ssnTextField.setText(personSsn);
    
    String personBirth=person.getDemographic().getBirth();
    birthTextField.setText(personBirth);
    
    String personPhoneNum=person.getDemographic().getPhoneNum();
    phoneTextField.setText(personPhoneNum);

}
        
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ssnTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        birthTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("View Demografic Info");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 182, -1, -1));

        ssnTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(ssnTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 164, -1));

        weightTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(weightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 164, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("LastName :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        firstnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        firstnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameTextFieldActionPerformed(evt);
            }
        });
        add(firstnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 164, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Age :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        birthTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(birthTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 164, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Phone number :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("FirstName :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Height :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        phoneTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 164, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Date of birth :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        heightTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(heightTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 164, -1));

        ageTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 164, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Social security number :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Weight :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        lastnameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(lastnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 164, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JTextField birthTextField;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
