/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
/**
 *
 * @author yanhongchen
 */
public class ViewPanel5 extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel5
     */
    private  Person person = new Person();
    public ViewPanel5(Person person) {
        initComponents();
        this.person=person;
        displayPerson(person);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void displayPerson(Person person){
        
    String personMedicalNum=person.getMedical().getMedicalNum();
    medicalNumTextField.setText(personMedicalNum);
    
    String personAlergy1=person.getMedical().getAlergy1();
    alergy1TextField.setText(personAlergy1);
    
    String personAlergy2=person.getMedical().getAlergy2();
    alergy2TextField.setText(personAlergy2);
    
    String personAlergy3=person.getMedical().getAlergy3();
    alergy3TextField.setText(personAlergy3);
    
}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        alergy1TextField = new javax.swing.JTextField();
        alergy2TextField = new javax.swing.JTextField();
        alergy3TextField = new javax.swing.JTextField();
        medicalNumTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("View Medical Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 80, 290, 33));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Alergy 1 :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 195, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Alergy 2 :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 235, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Alergy 3 :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 275, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Medical Number :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 155, -1, -1));

        alergy1TextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(alergy1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 195, 130, -1));

        alergy2TextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(alergy2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 235, 130, -1));

        alergy3TextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(alergy3TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 275, 130, -1));

        medicalNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(medicalNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 155, 130, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alergy1TextField;
    private javax.swing.JTextField alergy2TextField;
    private javax.swing.JTextField alergy3TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField medicalNumTextField;
    // End of variables declaration//GEN-END:variables
}
