/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import java.awt.Image;
import javax.swing.ImageIcon;
/**
 *
 * @author yanhongchen
 */
public class ViewPanel4 extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel4
     */
    private  Person person = new Person();
    public ViewPanel4 (Person person) {
        initComponents();
        this.person=person;
        displayPerson(person);
    }
    private void displayPerson(Person person){
    String personLicenseNum=person.getDriver().getLicenseNum();
    licenseNumTextField.setText(personLicenseNum);
    
    String personIssuedDate=person.getDriver().getIssuedDate();
    issuedDateTextField.setText(personIssuedDate);
    
    String personExpirationDate=person.getDriver().getExpirationDate();
    expirationDateTextField.setText(personExpirationDate);
    
    String personBloodType=person.getDriver().getBloodType();
    bloodTypeTextField.setText(personBloodType);
   
    ImageIcon icon= new ImageIcon(person.getDriver().getPicture());
    icon.setImage(icon.getImage().getScaledInstance(180, 160, Image.SCALE_DEFAULT));
    imageLable.setIcon(icon);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        imageLable = new javax.swing.JLabel();
        licenseNumTextField = new javax.swing.JTextField();
        issuedDateTextField = new javax.swing.JTextField();
        expirationDateTextField = new javax.swing.JTextField();
        bloodTypeTextField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel6.setText("View Driver License");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 9, 273, 38));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Picture :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 233, 150, 32));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Blood Type :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 191, 150, 32));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Expiration Dare :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 146, 150, 32));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Issued Date :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 101, 150, 32));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("License Number :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 56, -1, 32));

        imageLable.setBorder(javax.swing.BorderFactory.createTitledBorder("Person Image:"));
        add(imageLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 233, 153, 177));

        licenseNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(licenseNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 53, 159, 39));

        issuedDateTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(issuedDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 98, 159, 39));

        expirationDateTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(expirationDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 143, 159, 39));

        bloodTypeTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(bloodTypeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 188, 159, 39));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodTypeTextField;
    private javax.swing.JTextField expirationDateTextField;
    private javax.swing.JLabel imageLable;
    private javax.swing.JTextField issuedDateTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField licenseNumTextField;
    // End of variables declaration//GEN-END:variables
}
