/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;

/**
 *
 * @author yanhongchen
 */
public class ViewPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel2
     */
    private Person person = new Person();
     public ViewPanel2(Person person) {
        initComponents();
        this.person=person;
        displayAddress(person);
    }
     
    private void displayAddress(Person person){
    String personStreet=person.getAddress().getStreet();
    streetTextField.setText(personStreet);
    
    String personCity=person.getAddress().getCity();
    cityTextField.setText(personCity);
    
    String personState=person.getAddress().getState();
    stateTextField.setText(personState);
    
    String personZip=person.getAddress().getZip();
    zipTextField.setText(personZip);
    
    
   
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zipTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        zipTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(zipTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 164, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("StreetAddress :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        streetTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(streetTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 164, -1));

        stateTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 164, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("State :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("City :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("ZipCode :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        cityTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(cityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 164, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("View Address Info");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JTextField zipTextField;
    // End of variables declaration//GEN-END:variables
}
