/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
/**
 *
 * @author yanhongchen
 */
public class ViewPanel3 extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel3
     */ 
     private  Person person = new Person();
     public ViewPanel3(Person person) {
        initComponents();
        this.person=person;
        displayPerson(person);
    }
     
    private void displayPerson(Person person){
    String personSName=person.getBankaccount().getsName();
    sNameTextField.setText(personSName);
    
    String personSRoutingNum=person.getBankaccount().getsRoutingNum();
    sRoutingNumTextField.setText(personSRoutingNum);
    
    String personCAccountNum=person.getBankaccount().getcAccountNum();
    cAccountNumTextField.setText(personCAccountNum);
    
    String personSAccountBal=person.getBankaccount().getsAccountBal();
    sAccountBalTextField.setText(personSAccountBal);
    
    String personCRoutingNum=person.getBankaccount().getcRoutingNum();
    cRoutingNumTextField.setText(personCRoutingNum);
    
    String personCName=person.getBankaccount().getcName();
    cNameTextField.setText(personCName);
    
    String personCAccountBal=person.getBankaccount().getcAccountBal();
    cAccountBalTextField.setText(personCAccountBal);
    
    String personSAccountNum=person.getBankaccount().getsAccountNum();
    sAccountNumTextField.setText(personSAccountNum);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        sNameTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cRoutingNumTextField = new javax.swing.JTextField();
        sRoutingNumTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cNameTextField = new javax.swing.JTextField();
        cAccountNumTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sAccountNumTextField = new javax.swing.JTextField();
        cAccountBalTextField = new javax.swing.JTextField();
        sAccountBalTextField = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 450));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setText("Checking Account Number:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        sNameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(sNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 64, 164, -1));

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel12.setText("Checking Account Balence:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setText("Checking Account Name :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setText("Saving Account Balence :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Saving Account Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 70, -1, -1));

        cRoutingNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(cRoutingNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 301, 164, -1));

        sRoutingNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(sRoutingNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 104, 164, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setText("Checking Routing Number :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        cNameTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(cNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 261, 164, -1));

        cAccountNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(cAccountNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 341, 164, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel1.setText("View Checking Account");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 224, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jLabel3.setText("View Saving Account");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("Saving Routing Number :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("Saving Account Number : ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        sAccountNumTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(sAccountNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 144, 164, -1));

        cAccountBalTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(cAccountBalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 381, 164, -1));

        sAccountBalTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add(sAccountBalTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 184, 164, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cAccountBalTextField;
    private javax.swing.JTextField cAccountNumTextField;
    private javax.swing.JTextField cNameTextField;
    private javax.swing.JTextField cRoutingNumTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField sAccountBalTextField;
    private javax.swing.JTextField sAccountNumTextField;
    private javax.swing.JTextField sNameTextField;
    private javax.swing.JTextField sRoutingNumTextField;
    // End of variables declaration//GEN-END:variables
}
