/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Role.BookSupplier;
import Business.Role.Customer;
import Business.UserAccount.User;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author chenchen
 */
public class RegisterPanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private String type = "customer";
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel(EcoSystem system, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.rightPanel = rightPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ptxtPd = new javax.swing.JPasswordField();
        lbRegister = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbPd = new javax.swing.JLabel();
        lbRepd = new javax.swing.JLabel();
        ptxtRepd = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();

        lbRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRegister.setText("Customer Register");

        lbUsername.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbUsername.setText("Username: ");

        lbPd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbPd.setText("Password: ");

        lbRepd.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbRepd.setText("Password Confirm: ");

        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbRepd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ptxtRepd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ptxtPd, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(lbRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPd)
                    .addComponent(ptxtPd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRepd)
                    .addComponent(ptxtRepd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(btnRegister)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        char[] passwordCharArray = ptxtPd.getPassword();
        String password = String.valueOf(passwordCharArray);
        char[] rePasswordCharArray = ptxtRepd.getPassword();
        String rePd = String .valueOf(rePasswordCharArray);
        
        if(username==null||username.equals("")){
            JOptionPane.showMessageDialog(null,"Username Field can not be empty", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(password==null||password.equals("")){
            JOptionPane.showMessageDialog(null,"Password Field can not be empty", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!password.equals(rePd)){
            JOptionPane.showMessageDialog(null,"Please match password again!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        long id = getGenerateID();
        User user = new Customer(id,username,password);
        user.setType(type);
        user.setUserID(id);
        user.setUsername(username);
        user.setPassword(password);
        system.getUserAccountDirectory().getUserAccountList().add(user);
        dB4OUtil.storeSystem(system);
        
        txtUsername.setText("");
        ptxtPd.setText("");
        ptxtRepd.setText("");
        JOptionPane.showMessageDialog(null, "Register Successfully\nYour User Account ID is "+id);
        System.out.println("userid is: "+id);
    }//GEN-LAST:event_btnRegisterActionPerformed

    public static Long getGenerateID(){
         String sformat = "ddhhmmss";
         int num = 3;
         
         Date currentTime = new Date();
         SimpleDateFormat formatter = new SimpleDateFormat(sformat);
         String dateString = formatter.format(currentTime);
         String numStr = "";
         for(int i = 0; i < num; i++){
             numStr += (int)(10*(Math.random()));
         }
         
         String idStr = dateString + numStr;
         Long id = Long.valueOf(idStr);
         return id;
     }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lbPd;
    private javax.swing.JLabel lbRegister;
    private javax.swing.JLabel lbRepd;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPasswordField ptxtPd;
    private javax.swing.JPasswordField ptxtRepd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
