/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee;

import Business.Book.Book;
import Business.Comment.BookComment;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.CommunityOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanhongchen
 */

public class AddCommentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCommentsPanel2
     */
    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private Employee employee;
    private CommunityOrganization organization;
    public AddCommentsPanel(EcoSystem system, Employee employee, JPanel rightPanel) {
        initComponents();
        initComponents();
        this.system = system;
        this.rightPanel = rightPanel;
        this.employee = employee;
        this.organization = (CommunityOrganization)employee.getOrg();
        refreshTable();
    }
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel)UserCommentList.getModel();
        model.setRowCount(0);
        for(BookComment comment : organization.getBookCommentList()){
            Object[] row = new Object[model.getColumnCount()];
            row[0] = comment;
            row[1] = comment.getCommentID();
            row[2] = comment.getContent();
            row[3] = comment.getLike();
            row[4] = comment.getDateCreated();
            model.addRow(row);
        }
    }
    public double calculateBookRating(Book book){
        int like = 0;
        if(book.getBookCommentList().isEmpty()){
            Double doubleLike = (double)like;
            return doubleLike;
        }else{
        for(BookComment bookComment : book.getBookCommentList()){
            like += bookComment.getLike();
        }
            Double doubleLike = (double)like;
            return doubleLike;    
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserCommentList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        commentDetailTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserCommentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "CommentID", "Comment", "like", "PublishDate"
            }
        ));
        jScrollPane1.setViewportView(UserCommentList);
        if (UserCommentList.getColumnModel().getColumnCount() > 0) {
            UserCommentList.getColumnModel().getColumn(3).setPreferredWidth(5);
            UserCommentList.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 530, 180));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 40));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton2.setText("Check Comment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, 40));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setText("save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 100, 40));

        commentDetailTxt.setEnabled(false);
        add(commentDetailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 440, 40));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Comments Waiting List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Comment:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CommunityManagerWorkArea panel = new CommunityManagerWorkArea(system,employee,rightPanel);
        rightPanel.add("CommunityManagerWorkArea", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = UserCommentList.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookComment bookcomment = (BookComment)UserCommentList.getValueAt(row, 0);
        commentDetailTxt.setText(bookcomment.getContent());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = UserCommentList.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookComment bookComment = (BookComment)UserCommentList.getValueAt(row, 0);
        Double doubleLike = (double)bookComment.getLike();
        int bookID = bookComment.getBookID();
        
        for (Book book : system.getBookDirectory().getBookList()){
            if(book.getBookID() == bookID){
                int bookCommentSize = book.getBookCommentList().size();
                double bookRating = (calculateBookRating(book)+doubleLike)/(bookCommentSize+1);      
                book.setRating(bookRating);
                book.getBookCommentList().add(bookComment);
                organization.getBookCommentList().remove(bookComment);
                refreshTable();
            }
        }
        JOptionPane.showMessageDialog(null, "Comment add successfully!");
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserCommentList;
    private javax.swing.JTextField commentDetailTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
