/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee;

import Business.EcoSystem;
import Business.Employee.Employee;
import Interface.Sales.Process.BookStoreItemListPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author chenchen
 */
public class CommunityManagerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CommunityManagerWorkArea
     */
    private javax.swing.JPanel rightPanel;
    private EcoSystem system;
    private Employee employee;
    public CommunityManagerWorkArea(EcoSystem system, Employee employee, JPanel rightPanel) {
        initComponents();
        this.employee=employee;
        this.system=system;
        this.rightPanel=rightPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        addCommnetbtn = new javax.swing.JButton();
        btnCommunity1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Love Read Application System");
        lbTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 56, 494, 89));

        addCommnetbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addCommnetbtn.setText("Add user comments");
        addCommnetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommnetbtnActionPerformed(evt);
            }
        });
        add(addCommnetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 217, 494, 33));

        btnCommunity1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCommunity1.setText("Delete user comments");
        btnCommunity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunity1ActionPerformed(evt);
            }
        });
        add(btnCommunity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 285, 494, 33));
    }// </editor-fold>//GEN-END:initComponents

    private void addCommnetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommnetbtnActionPerformed
        // TODO add your handling code here:AddCommentsPanel
        AddCommentsPanel panel = new AddCommentsPanel(system,employee,rightPanel);
        rightPanel.add("AddCommentsPanel2", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_addCommnetbtnActionPerformed

    private void btnCommunity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunity1ActionPerformed
        // TODO add your handling code here:DeleteCommentsPanel
        DeleteCommentsPanel panel = new DeleteCommentsPanel(system,employee,rightPanel);
        rightPanel.add("DeleteCommentsPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnCommunity1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCommnetbtn;
    private javax.swing.JButton btnCommunity1;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
