/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee;

import Business.Book.Book;
import Business.Comment.BookComment;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.BookStoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.CommunityOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanhongchen
 */
public class DeleteCommentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteCommentsPanel
     */
    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private Employee employee;
    private CommunityOrganization communityOrganization;
    public DeleteCommentsPanel(EcoSystem system, Employee employee, JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.rightPanel = rightPanel;
        this.employee = employee;
        this.communityOrganization = (CommunityOrganization)employee.getOrg();
        populate(); 
    }
    
    
    public void populate(){
        DefaultTableModel model = (DefaultTableModel) UserCommentList.getModel();
        model.setRowCount(0);
        for(Book book : system.getBookDirectory().getBookList()){
            for(BookComment bookcomment: book.getBookCommentList()){
                Object[] row = new Object[model.getColumnCount()];
                row[0] = bookcomment;
                row[1] = bookcomment.getCommentID();
                row[2] = book;
                row[3] = bookcomment.getContent();
                row[4] = bookcomment.getDateCreated();
                model.addRow(row);
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        UserCommentList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        commentDetailTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserCommentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserID", "CommentID", "BookName", "Comment", "PublishDate"
            }
        ));
        jScrollPane1.setViewportView(UserCommentList);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 570, 170));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, 40));

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton2.setText("Check Comment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 40));

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 100, 40));

        commentDetailTxt.setEnabled(false);
        add(commentDetailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 470, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Comment:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Comments List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CommunityManagerWorkArea panel = new CommunityManagerWorkArea(system,employee,rightPanel);
        rightPanel.add("CommunityManagerWorkArea", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int row = UserCommentList.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookComment bookcomment = (BookComment)UserCommentList.getValueAt(row, 0);
        commentDetailTxt.setText(bookcomment.getContent());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = UserCommentList.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookComment bookComment = (BookComment)UserCommentList.getValueAt(row, 0);
        for(int i=0; i<system.getBookDirectory().getBookList().size();i++){
            Book book = system.getBookDirectory().getBookList().get(i);
            for(int j=0; j < book.getBookCommentList().size();j++){
                BookComment bookcommentExample =  book.getBookCommentList().get(j);
                if(bookComment.getCommentID() == bookcommentExample.getCommentID()){
                    if(book.getBookCommentList().size()-1 > 0){
                    Double newRating=(book.getRating()*book.getBookCommentList().size()-bookcommentExample.getLike())/(book.getBookCommentList().size()-1);
                    book.setRating(newRating);
                    }else{
                    book.setRating(0);
                    }
                    book.getBookCommentList().remove(bookcommentExample);                    
            }           
            }
        }
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Comment delete successfully!");
        populate(); 
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserCommentList;
    private javax.swing.JTextField commentDetailTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
