/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Employee;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chenchen
 */
public class EmployeeWorkQueueOutPanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private Employee employee;
    private Organization organization;
    private Network network;
    private Enterprise enterprise;
    /**
     * Creates new form EmployWorkQueueOutPanel
     */
    public EmployeeWorkQueueOutPanel(EcoSystem system, Employee employee, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.employee = employee;
        this.organization = employee.getOrg();
        this.rightPanel = rightPanel;
        network=null;
        enterprise = null;
        populateTable();
        cbNetTo.removeAllItems();
        cbNetTo.addItem(null);
        for(Network net : system.getNetworkList()){
            cbNetTo.addItem(net);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbQueue = new javax.swing.JTable();
        btnCheck = new javax.swing.JButton();
        txtReply = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        lbSend = new javax.swing.JLabel();
        txtSend = new javax.swing.JTextField();
        cbOrgTo = new javax.swing.JComboBox();
        lbTo = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        cbOrgTo1 = new javax.swing.JComboBox();
        cbNetTo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sent Date", "Message", "Receiver", "Reply Date", "Statue", "Reply"
            }
        ));
        jScrollPane1.setViewportView(tbQueue);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 53, 601, 150));

        btnCheck.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCheck.setText("Check Reply");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 232, 264, -1));

        txtReply.setEditable(false);
        add(txtReply, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 601, -1));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 232, 264, -1));

        lbSend.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbSend.setText("Send Request Message: ");
        add(lbSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));
        add(txtSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 427, -1));

        cbOrgTo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbOrgTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrgToActionPerformed(evt);
            }
        });
        add(cbOrgTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 410, 104, -1));

        lbTo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbTo.setText("Send To : ");
        add(lbTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 415, -1, -1));

        btnSend.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 408, 122, -1));

        cbOrgTo1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbOrgTo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrgTo1ActionPerformed(evt);
            }
        });
        add(cbOrgTo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 110, -1));

        cbNetTo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbNetTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNetToActionPerformed(evt);
            }
        });
        add(cbNetTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 410, 120, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Enterprise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Organization");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Network");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbQueue.getSelectedRow();
        WorkRequest selectedItem;
        if(selectedRow>=0){
            selectedItem = (WorkRequest) tbQueue.getValueAt(selectedRow, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a work request!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtReply.setText(selectedItem.getReply());
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbQueue.getSelectedRow();
        WorkRequest selectedItem;
        if(selectedRow>=0){
            selectedItem = (WorkRequest) tbQueue.getValueAt(selectedRow, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a work request!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        organization.getWorkQueue().getWorkRequestList().remove(selectedItem);
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Remove Work Request Successfully");
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        String mes = txtSend.getText();
        if(mes.equals("") || mes == null){
            JOptionPane.showMessageDialog(null, "Please input Message to be sent!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Organization org = (Organization)cbOrgTo.getSelectedItem();
        if(org == null){
            JOptionPane.showMessageDialog(null, "Please select the organization!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }else{
        WorkRequest re = new WorkRequest();
        re.setMessage(mes);
        re.setSender(organization);
        re.setReceiver(org);
        Date now = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy");
        String date = formatter.format(now);
        re.setRequestDate(date);
        organization.getWorkQueue().getWorkRequestList().add(re);
        if(!organization.equals(org)){
            org.getWorkQueue().getWorkRequestList().add(re);
        }
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Send Successfully");
        populateTable();
    }
    }//GEN-LAST:event_btnSendActionPerformed

    private void cbOrgToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrgToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrgToActionPerformed

    private void cbOrgTo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrgTo1ActionPerformed
        // TODO add your handling code here:
        enterprise = (Enterprise)cbOrgTo1.getSelectedItem();
        cbOrgTo.removeAllItems();
        cbOrgTo.addItem(null);
        if(enterprise == null){
           return;
        }
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            cbOrgTo.addItem(org);
        }
    }//GEN-LAST:event_cbOrgTo1ActionPerformed

    private void cbNetToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNetToActionPerformed
        // TODO add your handling code here:
        network = (Network)cbNetTo.getSelectedItem();
        cbOrgTo1.removeAllItems();
        cbOrgTo1.addItem(null);
        if(network==null){
            return;
        }
        for(Enterprise en : network.getEnterpriseDirectory().getEnterpriseList()){
            cbOrgTo1.addItem(en);
        }
    }//GEN-LAST:event_cbNetToActionPerformed

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbQueue.getModel();
        dtm.setRowCount(0);
        if(organization.getWorkQueue().getWorkRequestList().size()>0){
            for(WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
                if(organization.equals(request.getSender())){
                    Object row[] = new Object[6];
                    row[0] = request;
                    row[1] = request.getMessage();
                    row[2] = request.getReceiver();
                    row[3] = request.getResolveDate();
                    row[4] = request.getStatus();
                    row[5] = request.getReply();
                    dtm.addRow(row);
                }
            }
        }
    }
    
//    public void setOrgTo(){
//        cbOrgTo.removeAllItems();
//        for(Network net : system.getNetworkList()){
//            for(Enterprise ep : net.getEnterpriseDirectory().getEnterpriseList()){
//                for(Organization org : ep.getOrganizationDirectory().getOrganizationList()){
//                    cbOrgTo.addItem(org.getName());
//                }
//            }
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox cbNetTo;
    private javax.swing.JComboBox cbOrgTo;
    private javax.swing.JComboBox cbOrgTo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSend;
    private javax.swing.JLabel lbTo;
    private javax.swing.JTable tbQueue;
    private javax.swing.JTextField txtReply;
    private javax.swing.JTextField txtSend;
    // End of variables declaration//GEN-END:variables
}
