/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Sales.Process;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.BookStoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Item.Item;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanhongchen
 */
public class BookStoreSecondHandItemListPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookStoreSecondHandItemListPanel
     */
    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private Employee employee;
    private Enterprise enterprise;
    private BookStoreEnterprise bookStoreEnterprise;
    public BookStoreSecondHandItemListPanel(EcoSystem system, Employee employee, JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.rightPanel = rightPanel;
        this.employee = employee;
        this.enterprise = findEnterprise();
        this.bookStoreEnterprise = (BookStoreEnterprise) enterprise;
        refreshTable(); 
    }
    
        public Enterprise findEnterprise(){
        for(Network network : system.getNetworkList() ){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization :enterprise.getOrganizationDirectory().getOrganizationList()){
                    for(Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
                       if(this.employee.getId() == employee.getId()){
                            return enterprise;
                            
                       }
                    }
                }
            } 
        }
        return null;
    }
    
    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)BookListTable.getModel();
        model.setRowCount(0);
        
        for(Item item: bookStoreEnterprise.getOldBookDirectory().getItemList()){
            Object[] row = new Object[model.getColumnCount()];
            row[0] = item;
            row[1] = item.getBook().getBookID();
            row[2] = item.getType();
            row[3] = item.getQuantity();
            row[4] = item.getPrice();
            row[5] = item.getDescription();
            model.addRow(row);
        }
    }
        public void deleteImage(String imagePath){
        try{
            File file = new File(imagePath);
            if(file.delete()){
                System.out.println(file.getName() + " deleted successfully！");
            }else{
                System.out.println("File deletion failed！");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BookListTable = new javax.swing.JTable();
        jLabelList = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookListTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        BookListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookName", "BookID", "BookType", "BookQuantity", "BookPrice", "Description"
            }
        ));
        jScrollPane1.setViewportView(BookListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 83, 500, 199));

        jLabelList.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabelList.setText("Secondhand Item List");
        add(jLabelList, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        addBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        addBtn.setText("Add Item");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 323, 125, 45));

        deleteBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        deleteBtn.setText("Delete Item");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 393, 124, 45));

        returnBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        returnBtn.setText("<<Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 393, 124, 44));

        updateBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateBtn.setText("Update Item");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 323, 124, 45));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        AddSecondhandItemPanel panel = new AddSecondhandItemPanel(system,bookStoreEnterprise,employee,rightPanel);
        rightPanel.add("AddSecondhandItemPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row = BookListTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Item f = (Item)BookListTable.getValueAt(row, 0);
        String imagePath = f.getPicture();
        bookStoreEnterprise.getOldBookDirectory().getItemList().remove(f);
        deleteImage(imagePath);
        dB4OUtil.storeSystem(system);
        refreshTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int row = BookListTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Item i = (Item)BookListTable.getValueAt(row, 0);
        UpdateSecondhandItemPanel panel = new UpdateSecondhandItemPanel(system,i,rightPanel);
        rightPanel.add("UpdateSecondhandItemPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);

    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BookListTable;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabelList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
