/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer.Process;

import Business.Address.Address;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Role.Customer;
import Business.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chenchen
 */
public class FinishedOrdersPanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private User user;
    private Customer customer;
    /**
     * Creates new form FinishedOrdersPanel
     */
    public FinishedOrdersPanel(EcoSystem system, User user, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.user = user;
        this.customer = (Customer)user;
        this.rightPanel = rightPanel;
        showInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbItems = new javax.swing.JLabel();
        cbItems = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        lbAddr = new javax.swing.JLabel();
        lbTop = new javax.swing.JLabel();
        txtAddr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();

        lbItems.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbItems.setText("Order Items: ");

        cbItems.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbAddr.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbAddr.setText("Order Address: ");

        lbTop.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTop.setText("Orders in History");

        txtAddr.setEditable(false);
        txtAddr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Date", "Item Number", "Cost", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbOrder);

        btnDetail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDetail.setText("Check Details");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        lbID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbID.setText("Order ID: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbID)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbAddr, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbItems)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbItems, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDetail)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbItems)
                    .addComponent(cbItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAddr)
                    .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbOrder.getSelectedRow();
        Order selectedItem;
        if(selectedRow>=0){
            selectedItem = (Order) tbOrder.getValueAt(selectedRow, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select an order!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        txtID.setText(String.valueOf(selectedItem.getOrderID()));
        cbItems.removeAllItems();
        for(OrderItem oi : selectedItem.getOrderItemList()){
            cbItems.addItem(oi);
        }
        Address ad = selectedItem.getAddress();
        txtAddr.setText(ad.getStreet()+", "+ad.getCity()+", "+ad.getState()+", "+ad.getZip());
    }//GEN-LAST:event_btnDetailActionPerformed

    public void showInfo(){
        DefaultTableModel dtm = (DefaultTableModel) tbOrder.getModel();
        dtm.setRowCount(0);
        if(customer.getOrderList().size()>0){
            for(Order or : customer.getOrderList()){
                if(or.getStatus().equals("Finished")){
                    Object row[] = new Object[4];
                    row[0] = or;
                    row[1] = or.getOrderItemList().size();
                    row[2] = or.getTotalPrice();
                    row[3] = or.getStatus();
                    dtm.addRow(row);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDetail;
    private javax.swing.JComboBox cbItems;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAddr;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbItems;
    private javax.swing.JLabel lbTop;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
