/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer.Process;

import Business.Comment.ItemComment;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Role.Customer;
import Business.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chenchen
 */
public class OrderCommentPanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private User user;
    private Customer customer;
    private Order order;
    /**
     * Creates new form OrderCommentPanel
     */
    public OrderCommentPanel(EcoSystem system, User user, Order order, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.user = user;
        this.customer = (Customer)user;
        this.order = order;
        this.rightPanel = rightPanel;
        lbTop.setText("Say your experience,  "+user.getUsername());
        populateTable();
        areaComment.setLineWrap(true);
        areaComment.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lbTop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        lbRate = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        btnRating = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaComment = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbTop.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbTop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTop.setText("Say your experience, ");

        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Item", "Unit Price", "Quantity", "Rating"
            }
        ));
        jScrollPane1.setViewportView(tbItem);

        lbRate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbRate.setText("Rate the Item: ");

        btnRating.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRating.setText("Rating");
        btnRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRatingActionPerformed(evt);
            }
        });

        areaComment.setColumns(20);
        areaComment.setRows(5);
        jScrollPane2.setViewportView(areaComment);

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(lbTop, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRating, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jScrollPane2))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lbTop))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRate)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRating)
                    .addComponent(btnSubmit)
                    .addComponent(btnView))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRatingActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbItem.getSelectedRow();
        OrderItem selectedItem;
        if(selectedRow>=0){
            selectedItem = (OrderItem) tbItem.getValueAt(selectedRow, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select an item!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String strrate = txtRating.getText();
        double rating = 0;
        try{
            rating = Double.parseDouble(strrate);
            if(rating>10 || rating<0){
                JOptionPane.showMessageDialog(null, "Please input a number between 0 and 10!", "Alert", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a number between 0 and 10!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        selectedItem.setRating(rating);
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Rating Successfully");
        populateTable();
        txtRating.setText("");
    }//GEN-LAST:event_btnRatingActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbItem.getSelectedRow();
        OrderItem selectedItem;
        if(selectedRow>=0){
            selectedItem = (OrderItem) tbItem.getValueAt(selectedRow, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select an item!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        areaComment.setText(String.valueOf(selectedItem.getComment()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbItem.getSelectedRow();
        OrderItem selectedItem;
        if(selectedRow>=0){
            selectedItem = (OrderItem) tbItem.getValueAt(selectedRow, 0);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select an item!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ItemComment ic = new ItemComment(user.getUserID(),areaComment.getText(),order.getOrderID(),selectedItem.getOrderItemID());
        selectedItem.setComment(ic);
        selectedItem.getItem().getCommentList().add(ic);
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Submit Successfully");
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tbItem.getModel();
        dtm.setRowCount(0);
        for(OrderItem oi : order.getOrderItemList()){
            Object row[] = new Object[4];
            row[0] = oi;
            row[1] = oi.getItem().getPrice();
            row[2] = oi.getSaleQuantity();
            row[3] = oi.getRating();
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaComment;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRating;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbRate;
    private javax.swing.JLabel lbTop;
    private javax.swing.JTable tbItem;
    private javax.swing.JTextField txtRating;
    // End of variables declaration//GEN-END:variables
}
