/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ReadingCommunityPanel;

import Interface.ReadingCommunityPanel.ReadingCommunityHomePanel;
import Business.Book.Book;
import Business.Comment.BookComment;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.BookStoreEnterprise;
import Business.UserAccount.User;
import java.awt.CardLayout;
import static java.awt.Image.SCALE_DEFAULT;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanhongchen
 */
public class BookDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookDetailPanel
     */
    private EcoSystem system;
    private User user;
    private JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Book book;
    private BookStoreEnterprise  enterprise;
    public BookDetailPanel(EcoSystem system, BookStoreEnterprise bse,User user, Book book, JPanel rightPanel) {
        initComponents();
        this.rightPanel=rightPanel;
        this.system=system;
        this.user=user;
        this.book=book;
        this.enterprise = bse;
        showDetail();
        populate();
    }
    public void showDetail(){
        nameTxt.setText(book.getTitle());
        DecimalFormat df = new DecimalFormat("0.000");
        ratingTxt.setText(String.valueOf(df.format(book.getRating())));
        desArea.setText(book.getDescription());
        authorTxt.setText(book.getAuthor());
        ImageIcon icon = new ImageIcon(book.getPicture());
        icon.setImage(icon.getImage().getScaledInstance(144, 179, SCALE_DEFAULT));
        pictureLab.setIcon(icon);
    }
    public void populate(){
        DefaultTableModel model = (DefaultTableModel) commentTable.getModel();
        model.setRowCount(0);
        for(BookComment bookcomment : book.getBookCommentList()){
            Object[] row = new Object[model.getColumnCount()];
            row[0] = bookcomment;
            row[1] = bookcomment.getLike();
            row[2] = bookcomment.getDateCreated();
            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookNameLab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentTable = new javax.swing.JTable();
        pictureLab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desArea = new javax.swing.JTextArea();
        nameTxt = new javax.swing.JTextField();
        authorTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ratingTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        writeBtn = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookNameLab.setText("Name");
        add(BookNameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 40, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Book Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel2.setText("Author");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 60, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Book Comments Info");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        commentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Like Level", "Created Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(commentTable);
        if (commentTable.getColumnModel().getColumnCount() > 0) {
            commentTable.getColumnModel().getColumn(0).setResizable(false);
            commentTable.getColumnModel().getColumn(0).setPreferredWidth(15);
            commentTable.getColumnModel().getColumn(1).setResizable(false);
            commentTable.getColumnModel().getColumn(1).setPreferredWidth(15);
            commentTable.getColumnModel().getColumn(2).setResizable(false);
            commentTable.getColumnModel().getColumn(2).setPreferredWidth(75);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 410, 170));

        pictureLab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(pictureLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 140, 170));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        desArea.setColumns(20);
        desArea.setRows(5);
        desArea.setEnabled(false);
        jScrollPane1.setViewportView(desArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 360, 80));

        nameTxt.setEnabled(false);
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 170, 30));

        authorTxt.setEnabled(false);
        add(authorTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 170, 30));

        jLabel6.setText("Rating");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 50, 20));

        ratingTxt.setEnabled(false);
        ratingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingTxtActionPerformed(evt);
            }
        });
        add(ratingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 170, 30));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel7.setText("Description ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, 20));

        viewBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        viewBtn.setText("View Comment ");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        writeBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        writeBtn.setText("Create your own comment");
        writeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeBtnActionPerformed(evt);
            }
        });
        add(writeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        returnBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ratingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ratingTxtActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        ReadingCommunityHomePanel panel = new ReadingCommunityHomePanel(system,enterprise,user,rightPanel);
        rightPanel.add("ReadingCommunityHomePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void writeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        WriteCommentPanel panel = new WriteCommentPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("WriteCommentPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_writeBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:CommentDetailPanel
        int row = commentTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        BookComment bookcomment = (BookComment)commentTable.getValueAt(row, 0);
        CommentDetailPanel panel = new CommentDetailPanel(system,bookcomment,rightPanel);
        rightPanel.add("CommentDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookNameLab;
    private javax.swing.JTextField authorTxt;
    private javax.swing.JTable commentTable;
    private javax.swing.JTextArea desArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel pictureLab;
    private javax.swing.JTextField ratingTxt;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton writeBtn;
    // End of variables declaration//GEN-END:variables
}
