/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ReadingCommunityPanel;

import Business.Book.Book;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.BookStoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.UserAccount.User;
import Interface.Customer.CustomerHomePanel;
import java.awt.CardLayout;
import static java.awt.Image.SCALE_DEFAULT;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author yanhongchen
 */
public class ReadingCommunityHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form BookCommunityHomePanel
     */
    private EcoSystem system;
    private User user;
    private JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private BookStoreEnterprise  enterprise;
    private ArrayList<Book> list;
    public ReadingCommunityHomePanel(EcoSystem system, BookStoreEnterprise bse, User user, JPanel rightPanel) {
        initComponents();
        this.rightPanel=rightPanel;
        this.enterprise = bse;
        this.system=system;
        this.user=user;
        customerNameLab.setText("Hello:  "+user.getUsername());
        populateComboBox();
        showInfo();
    }


    private void populateComboBox() {
        BooklistComboBox.removeAllItems();
        for(Book book:system.getBookDirectory().getBookList())
            BooklistComboBox.addItem(book);
    }
    private void showInfo(){
        list = system.getBookDirectory().getBookList();
        Collections.sort(list);
        String[] title = new String[6];
        Double[] rating = new Double[6];
        ImageIcon[] icon = new ImageIcon[6];
        for(int i=0;i<6;i++){
            int id = list.get(i).getBookID();
            String path = list.get(i).getPicture();
            icon[i] = new ImageIcon(path);
            icon[i].setImage(icon[i].getImage().getScaledInstance(70, 103, SCALE_DEFAULT));
            for(Book b:system.getBookDirectory().getBookList()){
                if(id == b.getBookID()){
                    title[i] = b.getTitle();
                    rating[i] = b.getRating();
                    break;
                }
            }
        }
        DecimalFormat df = new DecimalFormat("0.000");
        rating1.setText(String.valueOf(df.format(rating[0])));
        rating2.setText(String.valueOf(df.format(rating[1])));
        rating3.setText(String.valueOf(df.format(rating[2])));
        rating4.setText(String.valueOf(df.format(rating[3])));
        rating5.setText(String.valueOf(df.format(rating[4])));
        rating6.setText(String.valueOf(df.format(rating[5])));
        
        title1Btn.setText(title[0]);
        title2Btn.setText(title[1]);
        title3Btn.setText(title[2]);
        title4Btn.setText(title[3]);
        title5Btn.setText(title[4]);
        title6Btn.setText(title[5]);
        
        icon1.setIcon(icon[0]);
        icon2.setIcon(icon[1]);
        icon3.setIcon(icon[2]);
        icon4.setIcon(icon[3]);
        icon5.setIcon(icon[4]);
        icon6.setIcon(icon[5]);
             
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BooklistComboBox = new javax.swing.JComboBox();
        viewBookBtn = new javax.swing.JButton();
        icon2 = new javax.swing.JLabel();
        icon5 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon6 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        title2Btn = new javax.swing.JButton();
        title3Btn = new javax.swing.JButton();
        title5Btn = new javax.swing.JButton();
        title1Btn = new javax.swing.JButton();
        title6Btn = new javax.swing.JButton();
        title4Btn = new javax.swing.JButton();
        customerNameLab = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        rating1 = new javax.swing.JLabel();
        rating2 = new javax.swing.JLabel();
        rating6 = new javax.swing.JLabel();
        rating4 = new javax.swing.JLabel();
        rating5 = new javax.swing.JLabel();
        rating3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Reading Community");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 180, -1));

        BooklistComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(BooklistComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 183, -1));

        viewBookBtn.setText("View Book ");
        viewBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookBtnActionPerformed(evt);
            }
        });
        add(viewBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        icon2.setBorder(javax.swing.BorderFactory.createTitledBorder("2"));
        add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 90, 130));

        icon5.setBorder(javax.swing.BorderFactory.createTitledBorder("5"));
        add(icon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 90, 130));

        icon1.setBorder(javax.swing.BorderFactory.createTitledBorder("1"));
        add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 130));

        icon3.setBorder(javax.swing.BorderFactory.createTitledBorder("3"));
        add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 90, 130));

        icon6.setBorder(javax.swing.BorderFactory.createTitledBorder("6"));
        add(icon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 90, 130));

        icon4.setBorder(javax.swing.BorderFactory.createTitledBorder("4"));
        add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 130));

        title2Btn.setText("jButton2");
        title2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title2BtnActionPerformed(evt);
            }
        });
        add(title2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 110, -1));

        title3Btn.setText("jButton2");
        title3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title3BtnActionPerformed(evt);
            }
        });
        add(title3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 110, -1));

        title5Btn.setText("jButton2");
        title5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title5BtnActionPerformed(evt);
            }
        });
        add(title5Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 110, -1));

        title1Btn.setText("jButton2");
        title1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title1BtnActionPerformed(evt);
            }
        });
        add(title1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 110, -1));

        title6Btn.setText("jButton2");
        title6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title6BtnActionPerformed(evt);
            }
        });
        add(title6Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 110, -1));

        title4Btn.setText("jButton2");
        title4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                title4BtnActionPerformed(evt);
            }
        });
        add(title4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 110, -1));

        customerNameLab.setText("<name>");
        add(customerNameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 160, -1));

        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        add(returnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, -1));

        rating1.setText("jLabel8");
        add(rating1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        rating2.setText("jLabel9");
        add(rating2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        rating6.setText("jLabel10");
        add(rating6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        rating4.setText("jLabel11");
        add(rating4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        rating5.setText("jLabel12");
        add(rating5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        rating3.setText("jLabel10");
        add(rating3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        jLabel14.setText("The best Book base on customer rating :");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel2.setText("Rating:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel3.setText("Rating:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        jLabel4.setText("Rating:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        jLabel5.setText("Rating:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel6.setText("Rating:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jLabel7.setText("Rating:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        CustomerHomePanel panel = new CustomerHomePanel(system,user,rightPanel);
        rightPanel.add("CustomerHomePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void viewBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookBtnActionPerformed
        // TODO add your handling code here:
        Book book =(Book)BooklistComboBox.getSelectedItem();        
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_viewBookBtnActionPerformed

    private void title1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title1BtnActionPerformed
        // TODO add your handling code here:
        Book book = list.get(0);
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_title1BtnActionPerformed

    private void title2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title2BtnActionPerformed
        // TODO add your handling code here:
        Book book = list.get(1);
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_title2BtnActionPerformed

    private void title3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title3BtnActionPerformed
        // TODO add your handling code here:
        Book book = list.get(2);
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_title3BtnActionPerformed

    private void title4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title4BtnActionPerformed
        // TODO add your handling code here:
        Book book = list.get(3);
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_title4BtnActionPerformed

    private void title5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title5BtnActionPerformed
        // TODO add your handling code here:
        Book book = list.get(4);
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_title5BtnActionPerformed

    private void title6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_title6BtnActionPerformed
        // TODO add your handling code here:
        Book book = list.get(5);
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_title6BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BooklistComboBox;
    private javax.swing.JLabel customerNameLab;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel rating1;
    private javax.swing.JLabel rating2;
    private javax.swing.JLabel rating3;
    private javax.swing.JLabel rating4;
    private javax.swing.JLabel rating5;
    private javax.swing.JLabel rating6;
    private javax.swing.JButton returnBtn;
    private javax.swing.JButton title1Btn;
    private javax.swing.JButton title2Btn;
    private javax.swing.JButton title3Btn;
    private javax.swing.JButton title4Btn;
    private javax.swing.JButton title5Btn;
    private javax.swing.JButton title6Btn;
    private javax.swing.JButton viewBookBtn;
    // End of variables declaration//GEN-END:variables
}
