/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ReadingCommunityPanel;

import Business.Book.Book;
import Business.Comment.BookComment;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.BookStoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.CommunityOrganization;
import Business.Organization.Organization;
import Business.UserAccount.User;
import Business.WorkQueue.ReadingCommunityWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yanhongchen
 */
public class WriteCommentPanel extends javax.swing.JPanel {

    /**
     * Creates new form WriteCommentPanel
     */
    private EcoSystem system;
    private User user;
    private JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private Book book;
    private BookComment bookComment;
    private BookStoreEnterprise  enterprise;
    public WriteCommentPanel(EcoSystem system,BookStoreEnterprise enterprise, User user, Book book,JPanel rightPanel) {
        initComponents();
        this.rightPanel=rightPanel;
        this.system=system;
        this.user=user;
        this.book=book;
        this.enterprise = enterprise;
        Radio1.setActionCommand("1");
        Radio2.setActionCommand("2");
        Radio3.setActionCommand("3");
        Radio4.setActionCommand("4");
        Radio5.setActionCommand("5");
    }

    public int createcommentId(){
        String sformat = "mmss";         
        Date currentTime = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat(sformat);
        String dateString = formatter.format(currentTime);
        String numStr = "";
        for(int i = 0; i < 4; i++){
             numStr += (int)(10*(Math.random()));
         } 
        String idStr = dateString + numStr;
        int id = Integer.valueOf(idStr);
        return id;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        sendBtn = new javax.swing.JButton();
        returnBtn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Radio2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Radio3 = new javax.swing.JRadioButton();
        Radio4 = new javax.swing.JRadioButton();
        Radio5 = new javax.swing.JRadioButton();
        Radio1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        sendBtn.setText("Send your comment to admin");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 310, -1));

        returnBtn2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        returnBtn2.setText("Return");
        returnBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtn2ActionPerformed(evt);
            }
        });
        add(returnBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 120, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Write your own comment ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        buttonGroup1.add(Radio2);
        Radio2.setText("2");
        Radio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio2ActionPerformed(evt);
            }
        });
        add(Radio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Chosse your like level");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, -1));

        buttonGroup1.add(Radio3);
        Radio3.setText("3");
        add(Radio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        buttonGroup1.add(Radio4);
        Radio4.setText("4");
        add(Radio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        buttonGroup1.add(Radio5);
        Radio5.setText("5");
        add(Radio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        buttonGroup1.add(Radio1);
        Radio1.setText("1");
        Radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio1ActionPerformed(evt);
            }
        });
        add(Radio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        commentArea.setColumns(20);
        commentArea.setRows(5);
        jScrollPane1.setViewportView(commentArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 380, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtn2ActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        BookDetailPanel panel = new BookDetailPanel(system,enterprise,user,book,rightPanel);
        rightPanel.add("BookDetailPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.previous(rightPanel);
    }//GEN-LAST:event_returnBtn2ActionPerformed

    private void Radio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio2ActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        if(commentArea.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Please write your comment");
        }else if(!Radio1.isSelected()&&!Radio2.isSelected()&&!Radio3.isSelected()&&!Radio4.isSelected()&&!Radio5.isSelected()){
        JOptionPane.showMessageDialog(null, "Please choose your like level");
        }else{ 
        String comment = commentArea.getText();
        String radioText = buttonGroup1.getSelection().getActionCommand(); 
        int like = Integer.valueOf(radioText);
        int BookID = book.getBookID();
        int commentId = createcommentId();
        long UserID = user.getUserID();
        CommunityOrganization co = null;
        this.bookComment = new BookComment(commentId, UserID, comment,BookID,like,new Date());
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(o.getType().equals(Organization.Type.Community)){
                co = (CommunityOrganization)o;
            }
        }
        if(co==null){
            JOptionPane.showMessageDialog(null, "Function Not Available Now!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ReadingCommunityWorkRequest rcw = new ReadingCommunityWorkRequest();
        rcw.setMessage("Comments from "+user.getUserID()+", bookID: "+BookID+", comment:"
                        +comment+":like level:"+like);
        rcw.setSender(co);
        rcw.setReceiver(co);
        Date now = new Date();
        SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-yyyy");
                String date = formatter.format(now);
                rcw.setRequestDate(date);
                rcw.setBookComment(bookComment);
                co.getWorkQueue().getWorkRequestList().add(rcw);
                co.getBookCommentList().add(bookComment);
        dB4OUtil.storeSystem(system);
        JOptionPane.showMessageDialog(null, "Successfully sent a comment");      
//        Double doubleLike = (double)like;
//        int bookCommentSize = book.getBookCommentList().size();
//        double bookRating = (calculateBookRating()+doubleLike)/(bookCommentSize+1);      
//        book.setRating(bookRating);
//        book.getBookCommentList().add(this.bookComment);
//        dB4OUtil.storeSystem(system);
         
        commentArea.setEnabled(false);
        sendBtn.setEnabled(false);
        Radio1.setEnabled(false);
        Radio2.setEnabled(false);
        Radio3.setEnabled(false);
        Radio4.setEnabled(false);
        Radio5.setEnabled(false);
        }
    }//GEN-LAST:event_sendBtnActionPerformed

    private void Radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Radio1;
    private javax.swing.JRadioButton Radio2;
    private javax.swing.JRadioButton Radio3;
    private javax.swing.JRadioButton Radio4;
    private javax.swing.JRadioButton Radio5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea commentArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnBtn2;
    private javax.swing.JButton sendBtn;
    // End of variables declaration//GEN-END:variables
}
