/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Interface.ReadingCommunityPanel.ReadingCommunityHomePanel;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.BookRecycleEnterprise;
import Business.Enterprise.BookStoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author chenchen
 */
public class CustomerHomePanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private User user;
    private Network network;
    private Enterprise enterprise;
    /**
     * Creates new form CustomerHomePanel
     */
    public CustomerHomePanel(EcoSystem system, User user, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.user = user;
        network = null;
        enterprise = null;
        this.rightPanel = rightPanel;
        lbUsername.setText("Hi, "+user.getUsername());
        cbNet.removeAllItems();
        cbNet.addItem(null);
        for(Network net : system.getNetworkList()){
            cbNet.addItem(net);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsername = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        btnCommunity = new javax.swing.JButton();
        btnShopping = new javax.swing.JButton();
        btnSelling = new javax.swing.JButton();
        cbNet = new javax.swing.JComboBox();
        lbArea = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbEnter = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUsername.setText("Username");
        add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 200, 31));

        lbWelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWelcome.setText("Welcome to Love Read Application");
        lbWelcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 494, 89));

        btnCommunity.setText("Reading Community");
        btnCommunity.setEnabled(false);
        btnCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityActionPerformed(evt);
            }
        });
        add(btnCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 32));

        btnShopping.setText("Book Store");
        btnShopping.setEnabled(false);
        btnShopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoppingActionPerformed(evt);
            }
        });
        add(btnShopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 134, 32));

        btnSelling.setText("Second-hand Book Market");
        btnSelling.setEnabled(false);
        btnSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellingActionPerformed(evt);
            }
        });
        add(btnSelling, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, 32));

        cbNet.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNetActionPerformed(evt);
            }
        });
        add(cbNet, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 137, -1));

        lbArea.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbArea.setText("Select Area: ");
        add(lbArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 89, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Enterprise: ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        cbEnter.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cbEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEnterActionPerformed(evt);
            }
        });
        add(cbEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 137, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        BookStoreEnterprise bse = (BookStoreEnterprise)enterprise;
        ReadingCommunityHomePanel panel = new ReadingCommunityHomePanel(system,bse,user,rightPanel);
        rightPanel.add("BookCommunityHomePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnCommunityActionPerformed

    private void btnShoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoppingActionPerformed
        // TODO add your handling code here:
        BookStoreEnterprise bse = (BookStoreEnterprise)enterprise;
        if(bse.getItemDirectory().getBookList().size()<6){
            JOptionPane.showMessageDialog(null, "The Store Is Not Available Now!", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        rightPanel.removeAll();
        ShoppingHomePanel panel = new ShoppingHomePanel(system,bse,user,rightPanel);
        rightPanel.add("ShoppingHomePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnShoppingActionPerformed

    private void btnSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellingActionPerformed
        // TODO add your handling code here:
        rightPanel.removeAll();
        BookRecycleEnterprise bre = (BookRecycleEnterprise)enterprise;
        CustomerSellPanel panel = new CustomerSellPanel(system,bre,user,rightPanel);
        rightPanel.add("CustomerSellPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnSellingActionPerformed

    private void cbNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNetActionPerformed
        // TODO add your handling code here:
        network = (Network)cbNet.getSelectedItem();
        cbEnter.removeAllItems();
        cbEnter.addItem(null);
        if(network==null){
            return;
        }
        for(Enterprise en : network.getEnterpriseDirectory().getEnterpriseList()){
            cbEnter.addItem(en);
        }
    }//GEN-LAST:event_cbNetActionPerformed

    private void cbEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEnterActionPerformed
        // TODO add your handling code here:
        enterprise = (Enterprise)cbEnter.getSelectedItem();
        if(network==null || enterprise==null){
            btnSelling.setEnabled(false);
            btnCommunity.setEnabled(false);
            btnShopping.setEnabled(false);
            return;
        }
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.BookStore)){
            btnCommunity.setEnabled(true);
            btnShopping.setEnabled(true);
            btnSelling.setEnabled(false);
        }
        else{
            btnSelling.setEnabled(true);
            btnCommunity.setEnabled(false);
            btnShopping.setEnabled(false);
        }
    }//GEN-LAST:event_cbEnterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunity;
    private javax.swing.JButton btnSelling;
    private javax.swing.JButton btnShopping;
    private javax.swing.JComboBox cbEnter;
    private javax.swing.JComboBox cbNet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables
}
