/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Customer;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.BookStoreEnterprise;
import Business.Item.Item;
import Business.Order.Order;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.Organization.SalesOrganization;
import Business.Role.Customer;
import Business.UserAccount.User;
import Interface.Customer.Process.CommentBrowsePanel;
import java.awt.CardLayout;
import static java.awt.Image.SCALE_DEFAULT;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author chenchen
 */
public class ViewItemPanel extends javax.swing.JPanel {

    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private BookStoreEnterprise enterprise;
    private User user;
    private Customer customer;
    private Item item;
    private String source = null;
    /**
     * Creates new form ViewItemPanel
     */
    public ViewItemPanel(EcoSystem system, BookStoreEnterprise enterprise, User user, Item item, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.enterprise = enterprise;
        this.user = user;
        this.customer = (Customer)user;
        this.item = item;
        this.rightPanel = rightPanel;
        showInfo();
    }
    
    public ViewItemPanel(EcoSystem system, BookStoreEnterprise enterprise, User user, Item item, String source, javax.swing.JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.enterprise = enterprise;
        this.user = user;
        this.customer = (Customer)user;
        this.item = item;
        this.source = source;
        this.rightPanel = rightPanel;
        showInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPicture = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        lbWelcome = new javax.swing.JLabel();
        lbAuthor = new javax.swing.JLabel();
        lbPoints = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescription = new javax.swing.JTextArea();
        btnComment = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        btnBuy = new javax.swing.JButton();
        lbPrice = new javax.swing.JLabel();

        lbPicture.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Title");

        lbWelcome.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWelcome.setText("Welcome, ");

        lbAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAuthor.setText("by Author");

        lbPoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPoints.setText("Points");

        areaDescription.setColumns(20);
        areaDescription.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        areaDescription.setRows(5);
        jScrollPane1.setViewportView(areaDescription);

        btnComment.setText("Browse Comments");
        btnComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommentActionPerformed(evt);
            }
        });

        btnCart.setText("Add to Cart");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        btnBuy.setText("But it Now");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        lbPrice.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(255, 0, 0));
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrice.setText("price");
        lbPrice.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                        .addComponent(lbWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnComment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbPicture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCart, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(btnBuy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lbWelcome))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCart, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnComment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if(source == null){
            rightPanel.removeAll();
            ShoppingHomePanel panel = new ShoppingHomePanel(system,enterprise,user,rightPanel);
            rightPanel.add("ShoppingHomePanel", panel);
            CardLayout cl = (CardLayout) rightPanel.getLayout();
            cl.previous(rightPanel);
        }
        else{
            rightPanel.remove(this);
            CardLayout cl = (CardLayout) rightPanel.getLayout();
            cl.previous(rightPanel);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
        if(item.getQuantity()>0){
            if(customer.getCartList().size()>0){  
                String ma = "d";
                for(OrderItem oi : customer.getCartList()){
                    if(item.equals(oi.getItem())){
                        int num = oi.getSaleQuantity();
                        oi.setSaleQuantity(num+1);
                        ma = "s";
                    }
                }
                if(ma.equals("d")){
                    int len = customer.getCartList().size();
                    OrderItem newoi = new OrderItem(len,item,1);
                    customer.getCartList().add(newoi);
                }
                
            }
            else{
                OrderItem newoi = new OrderItem(0,item,1);
                customer.getCartList().add(newoi);
            }
            dB4OUtil.storeSystem(system);
            JOptionPane.showMessageDialog(null, "Add to Cart Successfully");
        }
        else{
            JOptionPane.showMessageDialog(null, "Sorry, no product stored in inventory.\nYou can try to search in another store", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        if(item.getQuantity()<1){
            JOptionPane.showMessageDialog(null, "Sorry, no product stored in inventory.\nYou can try to search in another store", "Alert", JOptionPane.ERROR_MESSAGE);
            return;
        }
        OrderItem oi = new OrderItem(0,item,1);
        ArrayList<OrderItem> list = new ArrayList<>();
        list.add(oi);
        OrderPlacePanel panel = new OrderPlacePanel(system,user,list,rightPanel);
        rightPanel.add("OrderPlacePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        // TODO add your handling code here:
        CommentBrowsePanel panel = new CommentBrowsePanel(item,rightPanel);
        rightPanel.add("CommentBrowsePanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_btnCommentActionPerformed

    public void showInfo(){
        String username = user.getUsername();
        String title = item.getBook().getTitle();
        String author = item.getBook().getAuthor();
        double points = calPoints();
        item.setRating(points);
        double price = item.getPrice();
        String picPath = item.getPicture();
        String des = item.getDescription();
        
        lbWelcome.setText("Welcome,  "+username);
        lbTitle.setText(title);
        lbAuthor.setText("by  "+author);
        lbPoints.setText("Points: "+points);
        lbPrice.setText("$ "+price);
        areaDescription.setText(des);
        areaDescription.setEditable(false);
        ImageIcon icon = new ImageIcon(picPath);
        icon.setImage(icon.getImage().getScaledInstance(144, 179, SCALE_DEFAULT));
        lbPicture.setIcon(icon);
        
        areaDescription.setLineWrap(true);
        areaDescription.setWrapStyleWord(true);
        //rightPanel.add(new JScrollPane(areaDescription));
    }

    public double calPoints(){
        List<Order> list = enterprise.getOrderList();
        System.out.println(list.size());
        double avePoint = 0;
        double totalPoint = 0;
        int num = 0;
        for(Order or : list){
            for(OrderItem oi : or.getOrderItemList()){
                if(item.equals(oi.getItem())){
                    totalPoint = totalPoint + oi.getRating();
                    num++;
                }
            }
        }
        if(num == 0){
            avePoint = 8;
        }
        else{
            avePoint = totalPoint/num;
        }
        return avePoint;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescription;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnComment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAuthor;
    private javax.swing.JLabel lbPicture;
    private javax.swing.JLabel lbPoints;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbWelcome;
    // End of variables declaration//GEN-END:variables
}
