/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Administrator;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Administrator;
import Business.UserAccount.User;
import javax.swing.JPanel;

/**
 *
 * @author chenchen
 */
public class AdminOverviewPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminOverviewPanel
     */
    private EcoSystem system; 
    private User user;
    private JPanel rightPanel;
    private Administrator admin;
    public AdminOverviewPanel(EcoSystem system, User user, JPanel rightPanel) {
        initComponents();
        this.system= system;
        this.user = user;
        this.admin = (Administrator)user;
        this.rightPanel = rightPanel;
        int numEmp = 0;
        lbType.setText("Type:     "+ admin.getEnterprise().getEnterpriseType());
        lbEnter.setText("Enterprise:     "+admin.getEnterprise().getName());
        lbOrgN.setText("Organization Number:    "+admin.getEnterprise().getOrganizationDirectory().getOrganizationList().size());
        for(Organization organization : admin.getEnterprise().getOrganizationDirectory().getOrganizationList() ){
              numEmp += organization.getEmployeeDirectory().getEmployeeList().size();
           }           
        laEmp.setText("Employee Number:    "+numEmp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbOrgN = new javax.swing.JLabel();
        laEmp = new javax.swing.JLabel();
        lbEnter = new javax.swing.JLabel();
        lbType = new javax.swing.JLabel();

        lbTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Love Read Application System");
        lbTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbOrgN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbOrgN.setText("Organization Number: ");

        laEmp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        laEmp.setText("Employee Number: ");

        lbEnter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbEnter.setText("Enterprise: ");

        lbType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbType.setText("Type: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbOrgN, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(laEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbType, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbOrgN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(laEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel laEmp;
    private javax.swing.JLabel lbEnter;
    private javax.swing.JLabel lbOrgN;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbType;
    // End of variables declaration//GEN-END:variables
}
