/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Airliner;
import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FlightDirectory;
import java.awt.CardLayout;
import Interface.ManageAirliners.AgencyWorkAreaJPanel;
import Interface.ManageCustomer.CustomerWorkAreaJPanel;
import Interface.ManageFlights.AirlinerWorkAreaJPanel;
/**
 *
 * @author yanhongchen
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame1
     */
    private Airliner airliner;
    private AirlinerDirectory airlinerDirectory;
    private CustomerDirectory customerDirectory;
    private FlightDirectory flightDirectory;
    public MainJFrame() {
        initComponents();
        airliner = new Airliner();
        airlinerDirectory= new AirlinerDirectory();
        customerDirectory= new CustomerDirectory();
        flightDirectory = new FlightDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        ManageJPanel = new javax.swing.JPanel();
        Airlinerbtn = new javax.swing.JButton();
        AgencyBtn = new javax.swing.JButton();
        CustomerBtn = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Airlinerbtn.setText("Airliner Manager");
        Airlinerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerbtnActionPerformed(evt);
            }
        });

        AgencyBtn.setText("Agency Manager");
        AgencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgencyBtnActionPerformed(evt);
            }
        });

        CustomerBtn.setText("Customer Manager");
        CustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ManageJPanelLayout = new javax.swing.GroupLayout(ManageJPanel);
        ManageJPanel.setLayout(ManageJPanelLayout);
        ManageJPanelLayout.setHorizontalGroup(
            ManageJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CustomerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Airlinerbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgencyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ManageJPanelLayout.setVerticalGroup(
            ManageJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageJPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(AgencyBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Airlinerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomerBtn)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(ManageJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgencyBtnActionPerformed
        // TODO add your handling code here:
        AgencyWorkAreaJPanel agwaj = new AgencyWorkAreaJPanel(userProcessContainer, airlinerDirectory);
        userProcessContainer.add("AgencyWorkAreaJPanel",agwaj);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_AgencyBtnActionPerformed

    private void AirlinerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerbtnActionPerformed
        // TODO add your handling code here:
        AirlinerWorkAreaJPanel alwaj = new AirlinerWorkAreaJPanel(userProcessContainer, airlinerDirectory);
        userProcessContainer.add("AirlinerWorkAreaJPanel", alwaj);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AirlinerbtnActionPerformed

    private void CustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerBtnActionPerformed
        // TODO add your handling code here:
        CustomerWorkAreaJPanel cwaj = new CustomerWorkAreaJPanel(userProcessContainer, customerDirectory, airlinerDirectory, flightDirectory, airliner);
        userProcessContainer.add("CustomerWorkAreaJPanel", cwaj);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CustomerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgencyBtn;
    private javax.swing.JButton Airlinerbtn;
    private javax.swing.JButton CustomerBtn;
    private javax.swing.JPanel ManageJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
