/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageFlights;
import Business.Airliner;
import Business.Flight;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanhongchen
 */
public class MangeFlightCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MangeFlightCatalogJPanel
     */
    JPanel userProcessContainer;
    Airliner airliner;
    MangeFlightCatalogJPanel(JPanel userProcessContainer, Airliner airliner ) {
        initComponents();
        this.airliner=airliner;
        this.userProcessContainer=userProcessContainer; 
        AirlinerNameTextField.setText(airliner.getAirlinerName());
        refreshTable();   
    }
       public void refreshTable() {
        int rowCount = flightCatalog.getRowCount();
        DefaultTableModel model = (DefaultTableModel)flightCatalog.getModel();
        for(int i=rowCount-1;i>=0;i--) {
            model.removeRow(i);
        }
        
        for(Flight f : airliner.getFlightDirectory().getFlightDir()) {
            Object row[] = new Object[model.getColumnCount()];
            row[0] = f;
            row[1] = f.getDate();
            row[2] = f.getDateSection();
            row[3] = f.getOrigin();
            row[4] = f.getDestination();
            model.addRow(row);
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightCatalog = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AirlinerNameTextField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        flightNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Manage Flight Catalog");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        flightCatalog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        flightCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Flight Date", "Date Section", "Origin", "Destination"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(flightCatalog);
        if (flightCatalog.getColumnModel().getColumnCount() > 0) {
            flightCatalog.getColumnModel().getColumn(0).setResizable(false);
            flightCatalog.getColumnModel().getColumn(1).setResizable(false);
            flightCatalog.getColumnModel().getColumn(2).setResizable(false);
            flightCatalog.getColumnModel().getColumn(3).setResizable(false);
            flightCatalog.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 500, 170));

        viewBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        viewBtn.setText("View flight detail");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 230, -1));

        createBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        createBtn.setText("Create new flight");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 230, -1));

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBtn.setText("Search >>");
        searchBtn.setEnabled(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 120, -1));

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 230, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Airliner:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, 40));

        AirlinerNameTextField.setEditable(false);
        AirlinerNameTextField.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        AirlinerNameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AirlinerNameTextField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(102, 102, 102), null, null));
        AirlinerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirlinerNameTextFieldActionPerformed(evt);
            }
        });
        add(AirlinerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, 30));

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBtn.setText("Delete flight");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 230, -1));

        flightNameTextField.setEditable(false);
        flightNameTextField.setEnabled(false);
        add(flightNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 150, -1));

        jLabel3.setText("Choose the flight name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int row = flightCatalog.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight f = (Flight)flightCatalog.getValueAt(row, 0);
        ViewFlightDetailJPanel vfdjp = new ViewFlightDetailJPanel(userProcessContainer, f);
        userProcessContainer.add("ViewFlightDetailJPanel", vfdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewBtnActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        CreateNewFlightJPanel cnfjp = new CreateNewFlightJPanel(userProcessContainer, airliner);
        userProcessContainer.add("CreateNewFlightJPanel", cnfjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        flightNameTextField.setEditable(true);
        flightNameTextField.setEnabled(true);
        searchBtn.setEnabled(true);
    }//GEN-LAST:event_createBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        int row = flightCatalog.getRowCount();
        if(row<1) {
            JOptionPane.showMessageDialog(null, "Please create new filght", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight f;
        String flightName = flightNameTextField.getText();
        f = airliner.getFlightDirectory().searchFlight(flightName);
        ViewFlightDetailJPanel vfdjp = new ViewFlightDetailJPanel (userProcessContainer, f);
        userProcessContainer.add("ViewFlightDetailJPanel", vfdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        flightNameTextField.setText("");
    }//GEN-LAST:event_searchBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row = flightCatalog.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Flight f = (Flight)flightCatalog.getValueAt(row, 0);
        airliner.getFlightDirectory().removeFlight(f);
        refreshTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void AirlinerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirlinerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirlinerNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirlinerNameTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable flightCatalog;
    private javax.swing.JTextField flightNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
