/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.BookManager.Process;

import Business.Book.Book;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.BookStoreEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Interface.Employee.BookManagerWorkArea;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanhongchen
 */
public class EnterpriseBookListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplicationBookListPanel
     */
    private javax.swing.JPanel rightPanel;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private EcoSystem system;
    private Employee employee;
    private Enterprise enterprise;
    private BookStoreEnterprise bookStoreEnterprise;
    public EnterpriseBookListPanel(EcoSystem system, Employee employee, JPanel rightPanel) {
        initComponents();
        this.system = system;
        this.rightPanel = rightPanel;
        this.employee = employee;
        this.enterprise = findEnterprise();
        this.bookStoreEnterprise = (BookStoreEnterprise) enterprise;
        refreshTable();
    }

    public Enterprise findEnterprise(){
        for(Network network : system.getNetworkList() ){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                for(Organization organization :enterprise.getOrganizationDirectory().getOrganizationList()){
                    for(Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
                       if(this.employee.getId() == employee.getId()){
                            return enterprise;
                            
                       }
                    }
                }
            } 
        }
        return null;
    }
    
    
    public void refreshTable(){
        DefaultTableModel model = (DefaultTableModel)bookListTable.getModel();
        model.setRowCount(0);
        for(Book b: system.getBookDirectory().getBookList()){
        Object[] row = new Object[model.getColumnCount()];
        row[0] = b;
        row[1] = b.getBookID();
        row[2] = b.getAuthor();
        row[3] = b.getRating();
        model.addRow(row);
        }
    }
    public void deleteImage(String imagePath){
        try{
            File file = new File(imagePath);
            if(file.delete()){
                System.out.println(file.getName() + " deleted successfully！");
            }else{
                System.out.println("File deletion failed！");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookListTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        ReturnBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookName", "BookID", "BookAuthor", "bookRating"
            }
        ));
        jScrollPane1.setViewportView(bookListTable);
        if (bookListTable.getColumnModel().getColumnCount() > 0) {
            bookListTable.getColumnModel().getColumn(0).setPreferredWidth(130);
            bookListTable.getColumnModel().getColumn(1).setPreferredWidth(50);
            bookListTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            bookListTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 560, 190));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Book List");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        deleteBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        deleteBtn.setText("Delete Book");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 140, -1));

        updateBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateBtn.setText("Update Book");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 120, -1));

        addBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        addBtn.setText("Add Book");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 140, -1));

        ReturnBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ReturnBtn.setText("<<Return");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });
        add(ReturnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int row = bookListTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Book b = (Book)bookListTable.getValueAt(row, 0);
        deleteImage(b.getPicture());
        system.getBookDirectory().getBookList().remove(b);        
        dB4OUtil.storeSystem(system);
        refreshTable();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        // TODO add your handling code here:
        BookManagerWorkArea panel = new BookManagerWorkArea(system,employee,rightPanel);
        rightPanel.add("AdministratorOrganizationArea", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_ReturnBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int row = bookListTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Book b = (Book)bookListTable.getValueAt(row, 0);
        UpdateBookPanel panel = new UpdateBookPanel(system,b,rightPanel);
        rightPanel.add("UpdateBookPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        AddBookPanel panel = new AddBookPanel(system,rightPanel);
        rightPanel.add("AddBookPanel", panel);
        CardLayout cl = (CardLayout) rightPanel.getLayout();
        cl.next(rightPanel);
    }//GEN-LAST:event_addBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JTable bookListTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
