/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomer;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FlightDirectory;
import Business.Airliner;
import Business.Customer;
import Interface.ManageAirliners.ManageAirlinerJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author yanhongchen
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerWorkAreaJPanel
     */
    JPanel userProcessContainer;
    CustomerDirectory customerDirectory;
    AirlinerDirectory airlinerDirectory;
    FlightDirectory flightDirectory;
    Airliner airliner;
    public CustomerWorkAreaJPanel(JPanel userProcessContainer, CustomerDirectory customerDirectory, AirlinerDirectory airlinerDirectory, FlightDirectory flightDirectory ,Airliner airliner) {
        initComponents();
        this.airliner = airliner;
        this.customerDirectory=customerDirectory;
        this.userProcessContainer=userProcessContainer;
        this.airlinerDirectory=airlinerDirectory;
        this.flightDirectory=flightDirectory;
        customerComboBox.removeAllItems();
        refreshComboBox();
    }
        public void refreshComboBox(){
            for(Customer customer : customerDirectory.getCustomerDir()){
            customerComboBox.addItem(customer);
        }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MCBtn = new javax.swing.JButton();
        BTBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MCBtn.setText("GO>>");
        MCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCBtnActionPerformed(evt);
            }
        });
        add(MCBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 140, -1));

        BTBtn.setText("GO>>");
        BTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTBtnActionPerformed(evt);
            }
        });
        add(BTBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 140, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Customer   Work   Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("   Select Customer :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 217, -1, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Book Tickets :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, 30));

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboBoxActionPerformed(evt);
            }
        });
        add(customerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 140, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Manage Customer :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void MCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCBtnActionPerformed
        // TODO add your handling code here:
        ManageCustomerJPanel mcjp = new ManageCustomerJPanel(userProcessContainer,customerDirectory);
        userProcessContainer.add("ManageCustomerJPanel",mcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MCBtnActionPerformed

    private void BTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTBtnActionPerformed
        int row = (int) customerComboBox.getSelectedIndex();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a customer from the comboBox first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Customer customer = (Customer) customerComboBox.getSelectedItem();
        BookTicketJPanel btjp = new BookTicketJPanel(userProcessContainer,airlinerDirectory,flightDirectory,airliner, customer);
        userProcessContainer.add(" BookTicketJPanel",btjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BTBtnActionPerformed

    private void customerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBtn;
    private javax.swing.JButton MCBtn;
    private javax.swing.JComboBox customerComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
