/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ManageCustomer;

import Business.Customer;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
/**
 *
 * @author yanhongchen
 */
public class ViewCustomerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJpanel
     */
    JPanel userProcessContainer;
    Customer Costomer;
    ViewCustomerJPanel(JPanel userProcessContainer, Customer C) {
      initComponents();
      this.Costomer=C;
      this.userProcessContainer=userProcessContainer;
      nameTxtField.setText(C.getName());
      ageTxtField.setText(Integer.toString(C.getAge()));
      IDTxtField.setText(Integer.toString(C.getID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();
        Origin = new javax.swing.JLabel();
        IDTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("View  Customer  Detail");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 176, -1));

        backBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 150, -1));

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Age:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 100, 40));

        ageTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ageTxtField.setEnabled(false);
        ageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtFieldActionPerformed(evt);
            }
        });
        add(ageTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 210, -1));

        Origin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Origin.setText("ID:");
        add(Origin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 110, 30));

        IDTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDTxtField.setEnabled(false);
        add(IDTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 210, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, 30));

        nameTxtField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameTxtField.setEnabled(false);
        add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        nameTxtField.setEnabled(true);
        ageTxtField.setEnabled(true);
        IDTxtField.setEnabled(true);
        saveBtn.setEnabled(true);
        updateBtn.setEnabled(false);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCustomerJPanel manageCustomerJPanel = (ManageCustomerJPanel) component;
        manageCustomerJPanel.refreshTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
         if(nameTxtField.getText().isEmpty()||ageTxtField.getText().isEmpty()||IDTxtField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Empty content, Please recreate!");
            return;
        }
        try{
            Integer.parseInt(ageTxtField.getText());
            Integer.parseInt(IDTxtField.getText());
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "The age and ID of customer must be number ! ");
            return;
        }
        Costomer.setName(nameTxtField.getText());
        Costomer.setAge(Integer.parseInt(ageTxtField.getText()));
        Costomer.setID(Integer.parseInt(IDTxtField.getText()));
        JOptionPane.showMessageDialog(null, "Cusromer successfully uppdate", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void ageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDTxtField;
    private javax.swing.JLabel Origin;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
